### ISSUE TITLE
Alignment marking prevents scanning after update

### ISSUE THREAD

**Issue by LucaDiba** [SumiMakito/Awesome-qr.js#67] opened 2021-10-12 07:34 UTC
Hi, I'm using Awesome-qr.js on Vue (using vue-qr). I opened [an issue](https://github.com/Binaryify/vue-qr/issues/98) on that repo but it seems that the problem is on Awesome-qr.js. After an update I'm not able to scan the generated QR code anymore.

The problem is the change of the alignment marking (the little square at bottom-right):
![image](https://user-images.githubusercontent.com/34377738/136911293-b76b2d13-465f-4a9a-937d-ef687d42c0dc.png)

This is what is generated with the latest version. It's dotted and many scanning apps don't read it.
I tried to fill the space between the dots and it's possible to scan it again, so the problem is this one.

The issue seems to be the default value of the `dotScale` option (i see that is deprecated in this library so I'm not sure if it's still wrongly used). The default is 0.4, but if the value is changed to 1 (on vue-qr 1 is the default value), everything is scaled to 1 except from the alignment marking.

**Comment by SumiMakito** [comment] 2021-10-12 08:40
Hello and thanks for your feedback. 

In the latest version of awesome-qr on npm, the dotScale option has been marked as deprecated and will not be used in default unless the option is explicitly specified. After the inspection and testing, I found that the default values in prebuilt libraries under dist/ and lib/ differ from the ones specified in typescript files under src/. I think this might be caused by a mistake made by me while I was packing the previous version published on npm. 

I've rebuilt the libraries and published a new version (v2.1.5) to npm. Hopely this should fix this problem.

**Closed** 2021-12-11 08:28 UTC
